version: 2

sphinx:
  configuration: ldlm/conf.py

python:
  install:
  - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_checkout:
      - echo ${PY_LDLM_VERSION}
      - git submodule update --init --recursive
      - git --git-dir=./ldlm/py/py-ldlm/.git checkout tags/${PY_LDLM_VERSION}
